### ISSUE TITLE
Elaborate Readme

### ISSUE THREAD

**Issue by johannesh** [fastlane/docker#5]
Hey there,

I would love to use fastlane in a container in order to be more flexible with runners in our (GitLab) CI. I came here from https://hub.docker.com/r/fastlanetools/ci because I couldn't find any documentation there, in http://docs.fastlane.tools/ or in this repo.

It would be super useful to have at least a short summary of what this project is about (just internal use for testing or for the common use in CI systems and if so in which) and maybe one example of using the container.

Maybe it's super obvious and you have some other internal documentation, but with this repo being public a few more hints in the readme would be awesome for people like me and anyone intending to work with it.

**Comment by joshdholtz** [comment]
@johannesh Thanks for bringing this to my attention 😊 I’ve updated the README with a little bit more explanation on why this exists and where its used!
